### ISSUE TITLE
Error on 3.2.4

### ISSUE THREAD

**Issue by x1p** [xuancat0208/ExtendViewDistance#4]
Got this error. Though you like to be informed
```
[21:31:02 WARN]: java.util.ConcurrentModificationException
[21:31:02 WARN]: at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
[21:31:02 WARN]: at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
[21:31:02 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:544)
[21:31:02 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:31:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:31:02 WARN]: java.util.ConcurrentModificationException
[21:31:02 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:31:02 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:31:02 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:31:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:31:02 WARN]: java.util.ConcurrentModificationException
[21:31:02 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:31:02 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:31:02 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:31:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:31:02 WARN]: java.util.ConcurrentModificationException
[21:31:02 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:31:02 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:31:02 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:31:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:31:02 WARN]: java.util.ConcurrentModificationException
[21:31:02 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:31:02 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:31:02 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:31:02 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:02 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:31:02 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:31:02 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```
Or sometimes a smaller error:
```
[21:49:22 WARN]: java.util.ConcurrentModificationException
[21:49:22 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:49:22 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:49:22 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:49:22 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:49:22 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:49:22 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:49:22 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:49:22 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:49:22 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:49:22 WARN]: java.util.ConcurrentModificationException
[21:49:22 WARN]: at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
[21:49:22 WARN]: at java.base/java.util.Collection.removeIf(Collection.java:545)
[21:49:22 WARN]: at xuan.cat.ViewDistanceCat.d.b(Unknown Source)
[21:49:22 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:49:22 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:49:22 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:49:22 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:49:22 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:49:22 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```
Happens after teleporting
Config default
XuanCatAPI-3.0.2
ViewDistanceCat-3.2.4

**Comment by xuancat0208** [comment]
This project has been stopped for maintenance here
Want to get the High performance + multi-threading latest version
https://forum.gamer.com.tw/C.php?bsn=18673&snA=181915&tnum=57&subbsn=14

**Comment by xuancat0208** [comment]
https://www.mc-market.org/resources/13692/
